

name: CI

on:
  push:
  pull_request:
    
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-20
    steps:
      - uses: akv-platform/stale@debug
        with:
          debug-only: true
          delete-branch: true
