

name: CI

on:
  push:
  pull_request:
    
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: akv-platform/stale@edit-pr
        with:
          debug-only: true
          stale-pr-label: prstale
          days-before-pr-stale: 1
          #ignore-updates: true
          
