

name: CI

on:
  push:
  pull_request:
    
  workflow_dispatch:

permissions:
  contents: read # only for delete-branch option
  #issues: write
  pull-requests: write

jobs:
  test-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: 'Close PR'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          # curl -L -X  POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/akv-demo/test-stale/issues/4/comments -d "{\"body\":\"$(date)\"}"
          curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/akv-demo/test-stale/pulls/2 -d '{"title":"new title","body":"updated body 2","state":"closed","base":"main"}'
