

name: CI

on:
  push:
  pull_request:
    
  workflow_dispatch:

jobs:
  create-comment:
    runs-on: ubuntu-latest
    steps:
      - run: |
          set
          echo curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/akv-demo/test-stale/issues/4/comments -d "{\"body\":\"$(date)\"}"
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/akv-demo/test-stale/issues/4/comments -d "{\"body\":\"$(date)\"}"
