

name: CI

on:
  push:
  pull_request:
    
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: akv-platform/stale@main
        with:
          debug-only: true
          delete-branch: false
          ignore-updates: false
          days-before-close: 1
