

name: CI

on:
  push:
  pull_request:
    
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: akv-platform/stale@edit-pr
        with:
          debug-only: true
          days-before-stale: 1
          days-before-close: 2
          days-before-issue-stale: -1
          remove-stale-when-updated: true
          stale-pr-label: "stale"
          exempt-pr-labels: "no-stale"
          labels-to-remove-when-stale: "ready for review, ready to merge"
          stale-pr-message: >
            There hasn't been any activity on this pull request recently. 
            Therefore, this pull request has been automatically marked as stale
            and will be closed if no further activity occurs within **seven** days.
            Thank you for your contributions.
          
