

name: CI

on:
  push:
  pull_request:
    
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Downlod Artifacts 
        uses: actions/download-artifact@v3
  
      - uses: akv-platform/stale@apirate
        with:
          operations-per-run: 2
          debug-only: false
          delete-branch: false
