

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: akv-platform/stale@main

 
  build:
    if: ${{ false }}
    
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v3  

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
