

name: CI

on:
  push:
  pull_request:
    
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    env:
       NODE_DEBUG: http
    steps:
      # - uses: actions/checkout@v3
      - run: |
          mkdir /tmp/x
          echo 'aaaa' > /tmp/x/a
          
      - name: Cache
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: /tmp/x
          key: key-primes
  
      - uses: akv-platform/stale@apirate
        with:
          operations-per-run: 2
          debug-only: false
          delete-branch: false
          
