

name: CI

on:
  push:
  pull_request:
    
  workflow_dispatch:

permissions:
  contents: write # only for delete-branch option
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: akv-platform/stale@cache-miss
        with:
          debug-only: false
          operations-per-run: 4
          delete-branch: false
          ignore-updates: true
