

name: CI

on:
  push:
  pull_request:
    
  workflow_dispatch:

permissions:
  contents: read # only for delete-branch option
  issues: write
  pull-requests: write

jobs:
  create-comment:
    runs-on: ubuntu-latest
    steps:
      - name: 'get issue'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          # curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/akv-demo/test-stale/issues
          curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/akv-demo/test-stale/issues/11
