

name: CI

on:
  push:
  pull_request:
    
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: akv-platform/stale@v-sdolin/push-ref
        with:
          debug-only: true
          delete-branch: true
          ignore-updates: true
